/*Important business questions for sales analysis*/

--Sales and Revenue Analysis

/*Q1 What is the total revenue generated by the Flipkart?
how much money the business has earned from all customer purchases.*/

SELECT COALESCE(ROUND(SUM(line_revenue),2),0) AS Total_Revenue
FROM Orders as o
JOIN OrderItems as oi
ON o.order_id = oi.order_id
WHERE o.order_status = 'Delivered';

/*Q2 How many total orders and customers does the platform have?
how many orders have been placed and how many customers have shopped on the platform?*/

SELECT
    COUNT(DISTINCT order_id) as Total_orders,
    COUNT(DISTINCT customer_id) as Total_customers
FROM Orders;

/*Q3 What is the Average Order Value
how much a customer spends on average in a single order.*/

SELECT
    ROUND(
        SUM(line_revenue) /
        COUNT(DISTINCT order_id),
        2
    ) AS Average_Order_Value
FROM OrderItems;

/*Q4 Which month generated the highest revenue?
shows which months performed better in terms of sales*/

SELECT 
    DATENAME(MONTH , order_date) as 'Month',
    ROUND(SUM(oi.line_revenue),2) as Revenue
FROM Orders o
JOIN OrderItems oi
on o.order_id = oi.order_id
GROUP BY DATENAME(Month,order_date), Month(order_date)
ORDER BY Month(order_date);

/*Q5 What are the Top 10 highest revenue-generating orders?
identifies the most valuable orders placed on the platform.*/

SELECT TOP 10 order_id , ROUND(SUM(line_revenue),2) as Revenue
FROM OrderItems
GROUP BY order_id
ORDER BY Revenue DESC;

/*Q6 Which state generate the highest revenue?
identify the locations where customers contribute the most sales.*/

SELECT
    c.customer_state,
    ROUND(SUM(oi.line_revenue),2) AS Revenue
FROM Customers c
JOIN Orders o
ON c.customer_id=o.customer_id
JOIN OrderItems oi
ON o.order_id=oi.order_id
GROUP BY c.customer_state
ORDER BY Revenue DESC;

/*Q7 What is the monthly order growth trend?
shows whether the number of customer orders is increasing, decreasing, or remaining stable over time*/

SELECT
    FORMAT(CAST(order_date AS DATE),'yyyy-MM') AS [Month],
    COUNT(order_id) AS Orders
FROM Orders
GROUP BY FORMAT(CAST(order_date AS DATE),'yyyy-MM')
ORDER BY [Month];

--Customer Analysis

/* Q8. Who are the Top 10 highest spending customers?
Identifies VIP customers who contribute the most revenue and should be prioritized for loyalty programs.*/

SELECT TOP 10
    c.customer_id,
    ROUND(SUM(oi.line_revenue),2) AS Total_Spent
FROM Customers c
JOIN Orders o
ON c.customer_id=o.customer_id
JOIN OrderItems oi
ON o.order_id=oi.order_id
GROUP BY
    c.customer_id
ORDER BY Total_Spent DESC;


/* Q9. Which customers placed the highest number of orders?
identifies the most frequent buyers. */

SELECT TOP 10
    customer_id,
    COUNT(order_id) AS Total_Orders
FROM Orders
GROUP BY customer_id
ORDER BY Total_Orders DESC;

/*Q10. What is the average customer lifetime value (CLV)?
estimates how much revenue an average customer generates throughout their relationship with the business.*/

SELECT
    ROUND(
        AVG(CustomerRevenue),
        2
    ) AS Average_CLV
FROM
(
SELECT
customer_id,
SUM(oi.line_revenue) AS CustomerRevenue
FROM Orders o
JOIN OrderItems oi
ON o.order_id=oi.order_id
GROUP BY customer_id
)t;

/* Q11. Which age groups generate the highest revenue?
helps us understand which age groups contribute the most to sales.*/

SELECT
    Age_group,
    ROUND(SUM(oi.line_revenue),2) AS Revenue
FROM Customers c
JOIN Orders o
ON c.customer_id=o.customer_id
JOIN OrderItems oi
ON o.order_id=oi.order_id
GROUP BY age_group
ORDER BY Revenue DESC;

/* Q12. Which gender contributes more revenue?*/

SELECT 
    customer_gender ,
    ROUND(SUM(oi.line_revenue),2) as Revenue
FROM Customers c
JOIN Orders o
ON c.customer_id = o.customer_id
JOIN OrderItems oi
ON o.order_id = oi.order_id
GROUP BY customer_gender;

/* Q13. Which RFM customer segments contribute the highest revenue?
shows which customer groups generate the most revenue. */

SELECT
    Customer_segment,
    ROUND(SUM(Monetary),2) AS Revenue
FROM RFM_Segmentation
GROUP BY Customer_segment
ORDER BY Revenue DESC;

--Product & Category Analysis

/*Q14. Which product categories generate the highest revenue?
identify the categories that contribute the most to overall sales.*/

SELECT
    c.category_name,
    ROUND(SUM(oi.line_revenue),2) AS Revenue
FROM OrderItems oi
JOIN Products p
    ON oi.product_id = p.product_id
JOIN Categories c
    ON p.category_id = c.category_id
GROUP BY c.category_name
ORDER BY Revenue DESC;

/*Q15. Which products generate the highest revenue?
dentify the best-performing products in terms of sales value.*/

SELECT TOP 10
    p.product_name,
    ROUND(SUM(oi.line_revenue),2) AS Revenue
FROM OrderItems oi
JOIN Products p
    ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY Revenue DESC;

/*Q16. Which products are sold the most?
shows which products customers buy most frequently.
High-selling products indicate strong customer demand and should remain well-stocked*/

SELECT TOP 10
    p.product_name,
    SUM(oi.quantity) AS Total_Units_Sold
FROM OrderItems oi
JOIN Products p
    ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY Total_Units_Sold DESC;

/*Q17. Which categories have the highest average product rating?
helps identify which product categories provide the best customer experience 
and which categories may need quality improvements.*/

SELECT
    c.category_name,
    AVG(r.rating) AS Average_Rating
FROM Reviews r
JOIN Products p
    ON r.product_id = p.product_id
JOIN Categories c
    ON p.category_id = c.category_id
GROUP BY c.category_name
ORDER BY Average_Rating DESC;

/*Q18. Which categories have the highest return rates?
identifies product categories where customers return products more frequently,
helping the business investigate potential quality or expectation issues.*/

SELECT
    c.category_name,
    COUNT(r.return_id) AS Total_Returns
FROM Returns r
JOIN OrderItems oi
    ON r.order_id = oi.order_id and oi.product_id = r.product_id
JOIN Products p
    ON oi.product_id = p.product_id
JOIN Categories c
    ON p.category_id = c.category_id
GROUP BY c.category_name
ORDER BY Total_Returns DESC;

/* Q20. What are the most common reasons for product returns?
Understanding return reasons helps identify recurring customer issues 
and improve product quality, descriptions, or logistics.*/

SELECT
    return_reason,
    COUNT(*) AS Total_Returns
FROM Returns
GROUP BY return_reason
ORDER BY Total_Returns DESC;

--Payment Analysis

/*Q21. Which payment methods are used most frequently?
helps understand customer payment preferences
enabling the business to optimize payment options and promotional offers.*/

SELECT
    payment_type,
    COUNT(*) AS Total_Transactions
FROM Payments
GROUP BY payment_type
ORDER BY Total_Transactions DESC;

/*Q22. Which payment methods generate the highest revenue?
identifies which payment methods contribute the most to sales revenue
and helps evaluate payment channel performance.*/

SELECT
    p.payment_type,
    ROUND(SUM(oi.line_revenue),2) AS Revenue
FROM Payments p
JOIN Orders o
    ON p.order_id = o.order_id
JOIN OrderItems oi
    ON o.order_id = oi.order_id
GROUP BY p.payment_type
ORDER BY Revenue DESC;

/*Q23. What is the average transaction value by payment method?
compares the average spending of customers using different payment methods,
helping identify whether certain payment options are associated with higher-value purchases.*/

SELECT
    p.payment_type,
    ROUND(AVG(oi.line_revenue),2) AS Average_Transaction_Value
FROM Payments p
JOIN Orders o
    ON p.order_id = o.order_id
JOIN OrderItems oi
    ON o.order_id = oi.order_id
GROUP BY p.payment_type
ORDER BY Average_Transaction_Value DESC;

--Some Advanced Sql queries with additional business questions

/*Q24. Rank the Top 10 Customers by Total Spending
ranking helps identify the exact position of each customer based on total spending.
useful for loyalty programs and VIP customer recognition.*/

WITH CustomerRevenue AS
(
    SELECT
        o.customer_id,
        SUM(oi.line_revenue) AS Total_Revenue
    FROM Orders o
    JOIN Customers c
        ON o.customer_id = c.customer_id
    JOIN OrderItems oi
        ON o.order_id = oi.order_id
    GROUP BY
        o.customer_id
)

SELECT TOP 10
    DENSE_RANK() OVER(ORDER BY Total_Revenue DESC) AS Revenue_Rank,
    customer_id,
    ROUND(Total_Revenue,2) AS Total_Revenue
FROM CustomerRevenue;

/*Q25. Rank Products Within Each Category by Revenue
helps identify the best-selling products inside every category
instead of comparing all products together.*/

WITH ProductRevenue AS
(
    SELECT
        c.category_name,
        p.product_name,
        SUM(oi.line_revenue) AS Revenue
    FROM OrderItems oi
    JOIN Products p
        ON oi.product_id = p.product_id
    JOIN Categories c
        ON p.category_id = c.category_id
    GROUP BY
        c.category_name,
        p.product_name
)

SELECT
    category_name,
    product_name,
    ROUND(Revenue,2) AS Revenue,
    ROW_NUMBER() OVER
    (
        PARTITION BY category_name
        ORDER BY Revenue DESC
    ) AS Product_Rank
FROM ProductRevenue;


/*Q26. Compare Monthly Revenue with Previous Month
helps us understand whether revenue is increasing or decreasing compared to the previous month,
allowing the business to monitor growth trends.*/

WITH MonthlyRevenue AS
(
    SELECT
        CONVERT(char(7), o.order_date, 120) AS Order_Month,
        SUM(oi.line_revenue) AS Revenue
    FROM Orders o
    JOIN OrderItems oi
        ON o.order_id = oi.order_id
    GROUP BY CONVERT(char(7), o.order_date, 120)
)

SELECT
    Order_Month,
    ROUND(Revenue,2) AS Current_Revenue,
    ROUND(LAG(Revenue) OVER(ORDER BY Order_Month),2) AS Previous_Revenue,
    ROUND(
        Revenue - LAG(Revenue) OVER(ORDER BY Order_Month),
        2
    ) AS Revenue_Difference
FROM MonthlyRevenue
ORDER BY Order_Month;

/*Q27. Divide Customers into 5 Spending Groups
groups customers into spending levels (lowest to highest),
helping the business identify premium customers and design personalized marketing campaigns.*/

WITH CustomerRevenue AS
(
    SELECT
        o.customer_id,
        SUM(oi.line_revenue) AS Revenue
    FROM Orders o
    JOIN OrderItems oi
        ON o.order_id = oi.order_id
    GROUP BY o.customer_id
)

SELECT
    customer_id,
    ROUND(Revenue,2) AS Revenue,
    NTILE(5) OVER(ORDER BY Revenue DESC) AS Spending_Group
FROM CustomerRevenue;

/*Q28. Identify Customers Whose Spending is Above the Average Customer Spending
helps identify high-value customers who spend more than the average customer*/

WITH CustomerRevenue AS
(
    SELECT
        o.customer_id,
        SUM(oi.line_revenue) AS Revenue
    FROM Orders o
    JOIN OrderItems oi
        ON o.order_id = oi.order_id
    GROUP BY o.customer_id
)

SELECT
    customer_id,
    ROUND(Revenue,2) AS Revenue
FROM CustomerRevenue
WHERE Revenue >
(
    SELECT AVG(Revenue)
    FROM CustomerRevenue
)
ORDER BY Revenue DESC;

